Fix on non jupiter devices

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,7 +1,14 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
-systemctl enable --now jupiter-biosupdate.service || echo "jupiter-biosupdate service could not be enabled"
-systemctl enable --now jupiter-controller-update.service || echo "jupiter-controller-update service could not be enabled"
-systemctl enable --now jupiter-fan-control.service || echo "jupiter-fan-control service could not be enabled"
+if [[ ":Jupiter:" =~ "$(cat /sys/devices/virtual/dmi/id/product_name)" ]]
+then
+    systemctl enable --now jupiter-biosupdate.service || echo "jupiter-biosupdate service could not be enabled"
+    systemctl enable --now jupiter-controller-update.service || echo "jupiter-controller-update service could not be enabled"
+    systemctl enable --now jupiter-fan-control.service || echo "jupiter-fan-control service could not be enabled"
+    systemctl --global enable --now sdgyrodsu.service  || echo "sdgyrodsu service could not be enabled"
+    systemctl enable --now sdgyrodsu.service || echo "sdgyrodsu service could not be enabled"
+    systemctl --global enable --now jupiter-controller-update.service || echo "jupiter-controller-updatel service could not be enabled"
+    systemctl --global enable --now jupiter-fan-control.service || echo "jupiter-fan-control service could not be enabled"
+fi
diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,7 +1,13 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
 systemctl disable --now jupiter-biosupdate.service || echo "jupiter-biosupdate service could not be disabled"
 systemctl disable --now jupiter-controller-update.service || echo "jupiter-controller-update service could not be disabled"
 systemctl disable --now jupiter-fan-control.service || echo "jupiter-fan-control service could not be disabled"
+systemctl --global disable --now sdgyrodsu.service  || echo "sdgyrodsu service could not be disabled"
+systemctl disable --now sdgyrodsu.service || echo "sdgyrodsu service could not be disabled"
+systemctl --global disable --now jupiter-controller-update.service || echo "jupiter-controller-updatel service could not be disabled"
+systemctl --global disable --now jupiter-fan-control.service || echo "jupiter-fan-control service could not be disabled"
+rm /usr/lib/systemd/system/jupiter-controller-update.service || echo "jupiter-controller-update service could not be disabled"
+rm /usr/lib/systemd/system/jupiter-fan-control.service || echo "jupiter-fan-control service could not be disabled"
